spring:
  datasource:
    url: jdbc:h2:mem:k8sdemodb
    driver-class-name: org.h2.Driver
    username: admin
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

metrics:
  averagingperiod: 5.0

