apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sdemo-app
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8sdemo-app
  template:
    metadata:
      labels:
        app: k8sdemo-app
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: k8sdemo-app
          image: tungduongduc/k8sdemo-app:4.0-final
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health/status
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/status
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
