apiVersion: v1
kind: Service
metadata:
  name: k8sdemo-app-service
  namespace: application
spec:
  selector:
    app: k8sdemo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
